### ISSUE TITLE
Constant return values are not getting propagated through wrapper properties

### ISSUE THREAD

**Issue by eerhardt** [dotnet/linker#1318]
In a couple Http/System.Net EventSource classes, we have a [static wrapper property](https://github.com/dotnet/runtime/blob/4cb924de165aa8e5373a109a68611d422aa72a09/src/libraries/Common/src/System/Net/Logging/NetEventSource.Common.cs#L450-L451) that simply returns `Log.IsEnabled()`:

```C#
        public static new bool IsEnabled =>
            Log.IsEnabled();
```

We then have an [ILLink.Substitutions file](https://github.com/dotnet/runtime/blob/49ba698b434757493f16e191475559a09f72de9d/src/libraries/System.Private.CoreLib/src/ILLink/ILLink.Substitutions.Shared.xml#L5) that stubs out the `EventSource.IsEnabled()` method with a feature switch:

```xml
    <type fullname="System.Diagnostics.Tracing.EventSource" feature="System.Diagnostics.Tracing.EventSource.IsSupported" featurevalue="false">
      <method signature="System.Boolean get_IsSupported()" body="stub" value="false" />
      <method signature="System.Boolean IsEnabled()" body="stub" value="false" />
```

When linking with the feature switch set to `false`, the branches of the `static new bool IsEnabled` property are not being trimmed. This static property is staying untouched by the linker:

```
    .property bool IsEnabled()
    {
        .get bool System.Net.NetEventSource::get_IsEnabled()
        {
            IL_0000: ldsfld class System.Net.NetEventSource System.Net.NetEventSource::Log
            IL_0005: callvirt instance bool [System.Private.CoreLib]System.Diagnostics.Tracing.EventSource::IsEnabled()
            IL_000a: ret
        }
    }
```

And the `if` statements are being kept:

```C#
            set
            {
                if (value == null)
                {
                    throw new ArgumentNullException("value");
                }
                this.CheckDisposedOrStarted();
                if (NetEventSource.IsEnabled)
                {
                    NetEventSource.Associate(this, value, "InnerHandler");
                }
                this._innerHandler = value;
            }
```

This causes unnecessary code to be kept when EventSource is disabled.

We should propagate the constant return value through these properties, so we can trim even more code.

This is an alternative to https://github.com/dotnet/runtime/pull/38828

cc @marek-safar @vitek-karas @MichalStrehovsky

**Comment by vitek-karas** [comment]
The underlying reason is that `ConstantExpressionMethodAnalyzer` doesn't handle call instructions. The loop which "emulates" the IL stack is here: https://github.com/mono/linker/blob/811c69dfb6e325a344b713890408b137b39a888b/src/linker/Linker.Steps/RemoveUnreachableBlocksStep.cs#L1075. It handles jumps and such, but no calls. I honestly don't know if this is because at the time it was not a necessary feature, or if there's a deeper problem with it. I think it should be safe to handle calls to methods which are known to return constant values (substitution methods is a good example).

* We already rewrite IL based on the constant methods list, so doing it more is not in itself a problem
* We already limit the constant methods to either statics on non-virtual instance methods, so there's no potential for not determining the right target method for a call.
* We don't inline the call, we just inline the return value. So we would leave the calls in place - potential side effects would be preserved.

The potential downside is performance, this could lead to potentially many more methods being analyzed/rewritten which would slow down linker a lot.

**Comment by vitek-karas** [comment]
I'm actually wrong - linker already does this for simple cases. The problem is elsewhere. In this case the body of the static getter which linker sees (After substitutions) is:
```IL
        .get bool System.Net.NetEventSource::get_IsEnabled()
        {
            IL_0000: ldsfld class System.Net.NetEventSource System.Net.NetEventSource::Log
            IL_0005: ldc.i4.0
            IL_000a: ret
        }
```

So there's no "call" to handle. The problem is the `ldsfld` - currently the analyzer doesn't have a notion of "unknown value" nor it can correctly handle calls (note that there's no pop to replace the callvirt which would normally pop the implicit "this" parameter). 

This is harder to fix - we would have to somehow handle calls (to correctly pop arguments) and on top of that we would have to track "unknown" values in the hope that they will not affect the outcome of the method.

**Comment by vitek-karas** [comment]
The .NET 7 linker will do this correctly and remove the branches. There were several improvements to this area, I didn't try to track which exact change fixed this.
