### ISSUE TITLE
The linker should be smarter about how it handles ctor removal

### ISSUE THREAD

**Issue by davidfowl** [dotnet/linker#1399]
I've been thinking about this PR https://github.com/dotnet/runtime/pull/40227/files and wondering what scenarios would ever be valid where the linker keeps an interface IFoo and an implementation Foo : IFoo but deletes Foo's ctor because it never saw Foo get instantiated (maybe it happens via reflection). The savings from this seem minimal as you trim the constructor but the interface implementation is still there... Would it make sense to keep public constructors of interface implementations that are deemed preserved?

cc @eerhardt @vitek-karas @MichalStrehovsky @marek-safar

**Comment by MichalStrehovsky** [comment]
This is multiple things;

* If the type `Foo` is never seen as instantiated (e.g. no constructor was called), linker will often strip the `IFoo` from the interface list and remove all the implementation methods.
* There's exceptions though: for example, if an array of `Foo` was allocated somewhere (not `Foo` itself, just the array of it), linker can no longer strip `IFoo` from the interface list. This is because of variant casting (e.g. we need to be able to cast the `Foo[]` to `IFoo[]` and this wouldn't work if `IFoo` was removed from `Foo`'s interface list and you would get `InvalidCastException` for something that should just work.
* If you use `Foo` as a generic parameter somewhere, linker will automatically assume an array of it was created, because one can just have `T[]` somewhere and linker doesn't do the analysis necessary to disprove that (it would require analyzing the generic graph at instantiation level).
* If we keep the `IFoo` in the interface list, we also need to keep the methods that implement the interface, otherwise a `TypeLoadException` would occur at the first reference to `Foo` (e.g. when creating the array) because the type doesn't actually implement the interface.
* The linker can still strip the method bodies of the implementations - they can be replaced with e.g. `throw null`. I haven't validated this happens, but the infra is there and I believe it should.

Dragging in the constructors would bring in a lot more stuff (suddenly all interfaces would be considered used, all `ToString` overloads, etc.)

**Comment by marek-safar** [comment]
Which constructor would you keep? Keeping them all for a type which has interface seems wasteful. As Michal pointed out there are scenarios where we need to keep interface even if in practice is never used and this would make the scenario even worse.

**Comment by davidfowl** [comment]
All if them. Keeping the interface is fine, what I have a problem is keeping both the interface and implementation and then removing the constructors.

Using the DI in ASP.NET Core looks like this:

services.AddSingleton\<IFoo, Foo\>();
var sp = services.BuildServiceProvider();
var foo = sp.GetService\<IFoo\>();
foo.Bar();


With the above, we see Foo and IFoo and we see usage of specific IFoo methods but don't see the object creation but the linker decides to nuke all ctors which will make the code fail 100%. That's why I think it makes sense to be meek conservative here.

**Comment by MichalStrehovsky** [comment]
The linker will also nuke the implementations of the interface (or should, I haven't validated).

So:

```csharp
class Foo : IFoo, Bar
{
    public override string ToString() => ExpensiveFormatter.Format(this);

    int IFoo.Frob() => ExpensiveLogic.Do();
}
```

Actually becomes:

```csharp
class Foo : IFoo,
    // Also Bar gets hollowed out if it's not allocated
    Bar
{
    // ToString removed

    // body replace with a short stub
    int IFoo.Frob() => throw null;
}
```

If we were to keep the constructor just because the interface was used, linker wouldn't be able to touch any of the above and the before/after linking for this class would be identical.

For the purposes of this argument, try replacing `IFoo` with a common interface, like `IDisposable` or `IAsyncStateMachine`, or something similar.

**Comment by davidfowl** [comment]
> The linker will also nuke the implementations of the interface (or should, I haven't validated).

It doesn't.

So you're saying because an interface implementation exists, because it can't be constructed we should replace the guts of the 
implementation with stubs. Since that isn't happening today I assumed it make sense to preserve the constructor.

**Comment by mrvoorhe** [comment]
That behavior is enabled with the UnreachableBodies optimization.  Is that turned on by default for you guys?  cc @marek-safar @MichalStrehovsky .

**Comment by marek-safar** [comment]
@davidfowl changing linker to remove less is not the direction where we'd like to head. You are basically proposing that for example code like this (this is just one example you could play with generics, etc)

```c#
using System;

class X
{
    public static void Main ()
    {
        new C (null);
    }
}

interface II
{
}

class C : II
{
    public C (SomeHugeDependency arg)
    {
		// and even more dependencies here
    }

    public C (II ii)
    {
		if (ii != this)
			return;
    }
}
```

wound not be trimmed at all. We could add an option to disable this type of trimming but it won't be on by default.

**Comment by davidfowl** [comment]
I get it, I think this is the key:

> The linker will also nuke the implementations of the interface (or should, I haven't validated).

If the linker nuked interface implementations that weren't instantiated it would make sense to remove constructors.

**Comment by MichalStrehovsky** [comment]
> If the linker nuked interface implementations that weren't instantiated it would make sense to remove constructors

Right. It's a bug that this is not happening. As @mrvoorhe wrote above, linker has code that should do that (nuke the bodies) but it's not kicking in. We should fix that. We can use this issue to track that.

**Comment by davidfowl** [comment]
Got it!

**Comment by MichalStrehovsky** [comment]
> We can use this issue to track that.

Let's keep this open so that it's not lost :)

**Comment by MichalStrehovsky** [comment]
Oh, okay. So the UnreachableBodies optimization that I was referring to was actually disabled in #613 because it caused an issue in Xamarin that nobody investigated. This optimization would be able to eliminate the leftover interface implementation body (and more).

With this optimization enabled (add `-enable-opt unreachablebodies` to `_ExtraTrimmerArgs`), Linker can actually trim extra 7 % on David's [LinkedAspNetCoreApplication](https://github.com/davidfowl/LinkedAspNetCoreApplication). This looks like quite a significant saving to leave on the table.

There's one bug to fix because there's internal types in corelib that are not instantiated but have important instance methods (need to add `<assembly fullname="System.Private.CoreLib"><type fullname="System.SZArrayHelper" /></assembly>` to the trim xml to work around), but other than that the ASP.NET app still works.

@marek-safar Would you be able to spare someone on Xamarin to actually investigate what went wrong in #612? I can handle the CoreCLR side, but I'm not versed in debugging Xamarin stuff (happy to learn but trying to be efficient).

**Comment by mrvoorhe** [comment]
We've had UnreachableBodies enabled for months.  No issues yet...I think.  

We have 1 prototype bug fix waiting to be completed.  It's been a few weeks I can't remember the exact conditions needed to cause it.  I don't think it was unreachable bodies. But I set it aside until we sync up with `master` (in progress now).  I was changing code that I knew would conflict with master and I prefer to land fixes upstream first and then pull them back in to our fork.

**Comment by marek-safar** [comment]
@MichalStrehovsky as you noticed I trigger runtime build with the change first as that's easier for us to play with. If that does not trigger the bug(s) (I think it did last time we enable it) we'll go with the mobile path but that one is a bit more complicated to setup as not all pieces are up to date.

IIRC we had to disable this optimization even for Mono as it was causing problems

**Comment by vitek-karas** [comment]
The optimization is enabled by default in .NET 7 (probably was already enabled in .NET 6, didn't check). The above test case will keep the interface methods on the implementation type, but replace their bodies with a throw. All other members (including .ctors) are removed from the type as they're not referenced by anything.
