### ISSUE TITLE
Linker warns about compiler generated fields when using new reflection attributes

### ISSUE THREAD

**Issue by davidfowl** [dotnet/linker#1403]
Consider the following:

```C#
using System;
using System.Diagnostics.CodeAnalysis;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Create(typeof(Person));
        }

        static object Create([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)]Type t)
        {
            object Foo()
            {
                return Activator.CreateInstance(t);
            }

            return Foo();
        }
    }

    public class Person
    {
        public int Age { get; set; }
    }
}
```

It'll result in the following warning:

```
C:\Users\davifowl\source\repos\WebApplication60\ConsoleApp1\Program.cs(17,17): Trim analysis warning IL2006: ConsoleApp1.Program.<Create>g__Foo|1_0(<>c__DisplayClass1_0&): The field 'System.Type ConsoleApp1.Program/<>c__DisplayClass1_0::t' with dynamically accessed member kinds 'None' is passed into the parameter #0 of method 'System.Object System.Activator::CreateInstance(System.Type)' which requires dynamically accessed member kinds 'PublicParameterlessConstructor'. To fix this add DynamicallyAccessedMembersAttribute to it and specify at least these member kinds 'PublicParameterlessConstructor'. [C:\Users\davifowl\source\repos\WebApplication60\ConsoleApp1\ConsoleApp1.csproj]
```

Which makes sense but I can't annotate the closure fields since they are compiler generated. The linker warnings needs to be disabled for compiler generated types (or inferred as having the attribute which is really the same thing).

**Comment by MichalStrehovsky** [comment]
The .NET Native analyzer that the dataflow analysis in Linker is based on has infrastructure to flow data across some closures (e.g. the `async` state machines that I called out when bringing the code originally over in #994). The infrastructure wasn't brought over because this is V1 and can be worked around. Local functions are newer than .NET Native so there's no precedent for those in the .NET Native analyzer anyway.

Unfortunately this requires hardcoding Roslyn implementation details (without hardcoding those, we basically need a crossmethod dataflow analysis that models instance state - a pretty expensive feature).

I don't think this can make it into .NET 5.

The workaround is to place a suppression on the `Foo` method similar to e.g. how I did TypeInfo.GetDeclaredMethods here: https://github.com/dotnet/runtime/pull/38865/files#diff-f9c905a942565861ce4649a0c9afca28 (this was due to `yield return`).

**Comment by davidfowl** [comment]
Ah yes local functions can have attributes now. I have some code in lambdas that I didn't want to rewrite just to place the attribute.

**Comment by vitek-karas** [comment]
This should be fixed in .NET 7 - linker now correctly handles local functions and lambdas and "flows annotations" into the generated closures and such. Note that reflection access to compiler generated code is still producing warnings (we have to, since we can't guarantee all of the requirements), but we've made improvements in this are to limit that enough that it seems workable now. If there's still cases where the warning is produced and it can be avoided with reasonable effort, let's use a different issue to track that work.
