### ISSUE TITLE
Unable to build Trimmed app.

### ISSUE THREAD

**Issue by RomanHubyak** [dotnet/linker#1652]
![image](https://user-images.githubusercontent.com/46841287/100380136-e5f31f80-301e-11eb-9ab8-907e257b44b0.png)

I use https://github.com/zzzprojects/EntityFramework-Plus library which has an obfuscated dependency (Z.Expressions.Eval.dll, from where the issue comes). I receive this error when trying to build with `<PublishTrimmed>true</PublishTrimmed>`.

I use latest .Net 5, EF Core 5 and library versions.

**Comment by vitek-karas** [comment]
This is probably the same issue as https://github.com/mono/linker/issues/1741 which was recently fixed and backported to https://github.com/mono/linker/pull/1759. Can you please check if it still reproes with the next release of 5.0.x SDK?

**Comment by RomanHubyak** [comment]
@vitek-karas Which version of .NET SDK should I try? It still fails with 5.0.102.

**Comment by vitek-karas** [comment]
I think it should be in the next servicing release - I actually don't know if that will be 5.0.103 or 5.0.2XX. You can try the latest 5.0.2XX build from https://github.com/dotnet/installer.

**Comment by RomanHubyak** [comment]
SDK 5.0.201 - still not working.

**Comment by vitek-karas** [comment]
Thanks for letting us know. It was actually fixed in 5.0.104, but then something went wrong and the fix was removed from 5.0.2xx. We're getting it fixed, hopefully for both 5.0.2xx and 5.0.3xx (and onward).

I tested that adding a global.json to the project to force it to use SDK 5.0.104 will not fail (while using the latest 5.0 will fail).
