### ISSUE TITLE
Linker doesn't warn if RUC method is rooted via descriptor

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/linker#2103]
Root a method with `RequiresUnreferencedCode` via a descriptor. This should probably generate `IL2026`, but it currently doesn't.

**Comment by vitek-karas** [comment]
I'm not sure what the behavior should be here. The problem is that if the method is referenced directly, it would make sense to generate the warning. But if the method is marked indirectly by marking the entire owning type, it might not be desirable.

It's a similar problem to reporting RUC methods which are kept due to `copy` action for example (we don't report these).

@MichalStrehovsky @agocke @marek-safar

**Comment by mateoatr** [comment]
Why not keep the behavior of only emitting `IL2026` when the annotated member is directly called?

> if the method is marked indirectly by marking the entire owning type, it might not be desirable

Agreed. I think that as of today, we don't produce any warnings associated with types that are annotated with RUC.

```C#
[RequiresUnreferencedCode ("")]
class AnnotatedType() { }
```

I'd expect this (RUC-annotated types) to warn when being instantiated (either directly or indirectly) but not when calling its member functions.

**Comment by vitek-karas** [comment]
RUC on types is not yet supported: https://github.com/mono/linker/issues/1742
The plan for it is to work similarly to `ObsoleteAttribute`, which means - it's as if you put RUC on all constructors and all static members.

My main concern is if the RUC annotated method is directly referenced from the descriptor (not by including its declaring type, but directly targeting the method in question).

Note that a very similar problem applies to methods with DAM annotations - https://github.com/mono/linker/issues/1764

**Comment by MichalStrehovsky** [comment]
If we want to warn, we should probably be consistent - if there's a descriptor that says to keep everything in an assembly and any of the methods have RUC, we should warn.

The thing this warning protects us from is invalid suppressions - if there's reflection that illink cannot analyze and someone puts a suppression with `Justification = "This is fine because we root the entire assembly"` the warning is the thing saying "this is not fine".

But one can also look at it as a suppression bug - one can always author an invalid suppression that will make it look like things should work, but then they don't. The questions is only whether we would like to be able to put protections in place for at least some of those suppressions.

**Comment by tlakollo** [comment]
Reopening this discussion now that some of the linker stuff has been solved and NativeAOT already implemented some of the XML support. 

Currently, we have some inconsistent behavior when accessing members via the xml descriptor. In Linker if we keep a field via a descriptor and the class is annotated with Requires we would generate a warning. Also, this issue still holds up, when referencing a method via a descriptor file there is no warning generated. This also means that we cannot generate warnings for calling the constructor or static constructor of a class.
```C#
// Warning not being generated for the method 
// [LogContains ("--RequiresOnlyViaDescriptor--")]  // https://github.com/dotnet/linker/issues/2103

[ExpectedWarning ("IL2026", "RequiresOnFieldOnlyViaDescriptor.Field", FileName = "RequiresViaXml.descriptor.xml", ProducedBy = ProducedBy.Trimmer)]
class RequiresViaXml
{
  [RequiresUnreferencedCode ("Message for --RequiresOnlyViaDescriptor--")]
  static void RequiresOnlyViaDescriptor () { }
  [RequiresUnreferencedCode ("Message for --RequiresOnFieldOnlyViaDescriptor--")]
  class RequiresOnFieldOnlyViaDescriptor
  {
	  public static int Field;
  }
}
```
In NativeAOT we add members referenced in the descriptor to the dependency graph to keep them. But adding a direct dependency to the graph does not generate any kind of diagnostic. For example, in order to generate field diagnostics due to access (no xml descriptor involved), we determine if the field it's dataflow or Requires interesting, if it is interesting then we scan the eclosing method body using trimming dataflow techniques by injecting a DataflowAnalyzedMethodNode. 

In the case of the descriptor file, this is not possible because there is no call, no method body (and therefore it's not possible to inject a DataflowAnalyzerMethodNode), although we could generate the diagnostic directly on the xml reading logic or while capturing the dependencies of the field I think in general descriptor files describe members that need to be kept but not how they are being accessed. 

To me, the expected behavior should be not to generate a warning for any of the members kept via descriptor file. The usage of the descriptor file implies that there is something outside of the compiler scope for which we couldn't describe the reachability, and attempting to warn in these cases is something we shouldn't try do do.

**Comment by MichalStrehovsky** [comment]
It feels like we should have the same answers to all of these:

* RUC method is preserved because of DynamicDependency
* RUC method is preserved because of a descriptor
* RUC method is preserved because the assembly had a copy/copyused action specified on the command line

If we warn, we should warn in all. If we don't warn, we shouldn't warn for any. They all basically say that something not visible to analysis might access them. If it's not visible, trimming is not really responsive for it - not warning might be fine.

**Comment by tlakollo** [comment]
After a discussion with several members of the team, we have come to the conclusion that having warnings generated via descriptor or an assembly that had copy/copyused action brings not that much value, and if those warnings happen to be suppressed given that there is no origin member, they have to suppress the warning ID which can lead to breaking the app as it develops in the future. In the case of DynamicDependency the origin of the warning is whichever member happens to have the annotation, plus is tightly coupled at this moment with the DAM analysis. Therefore expected behavior will be to not warn for descriptors and assemblies that have copy/copyused as actions but do warn for DynamicDependency
