### ISSUE TITLE
.Net  MAUI Blazor Hybrid App Error when deploying to iphone12 simulator	IL1012	IL Linker has encountered an unexpected error

### ISSUE THREAD

**Issue by nssidhu** [dotnet/linker#2547]
I am using Visual studio 2022 17.1.0 Preview 2.0 with .NET MAUI Preview 12.
Also i am using .NET MAUI Blazor Template for my project.

I can successfully deploy the code to Android simulator without any error.
But when i run the code against iphone 12 max pro simulator (I am connected to MacOS Laptop) i get the following error it fails to start the emulator/simulator

Error	IL1012	IL Linker has encountered an unexpected error. Please report the issue at https://github.com/mono/linker/issues	BlazorHybrid	C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\15.0.101-preview.11.551\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets

**Comment by vitek-karas** [comment]
@jonathanpeppers could you please help with this one?
Maybe it's already known? (sounds like a relatively simple repro).

If not, would it be possible to get a more detailed error from this - linker will report it in the output. So just grabbing msbuild binlog (/bl) should be enough.
Or if we can repro this, even better.

**Comment by jonathanpeppers** [comment]
This looks like it could be something when deploying to iOS from Windows? Maybe @mauroa or @emaf could help?

**Comment by emaf** [comment]
This looks like a build error, but without a binlog it's difficult to know what could be causing this. (cc @rolfbjarne)

@nssidhu you can record a MSBuild binlog using the [Project System tools extension for VS](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools2022&ssr=false#overview), you can find steps to save the logs [here](https://github.com/dotnet/project-system-tools#features). 

Although this seems to be a problem on the SDK and updating probably won't fix this problem, I'd still recommend you to update to Visual Studio 2022 17.1.0 Preview 4 since there were several fixes and improvements.

**Comment by nssidhu** [comment]
Based on the output window, build was successful, there occurred during deploy.
Let me update visual studio and try it again.

**Comment by nssidhu** [comment]
Deleting bin & obj Folders manually  and then doing clean and rebuild helped resolve the issue.
