### ISSUE TITLE
RUC analyzer seems to react to nameof references

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/linker#2647]
```C#
[RUC("Don't")]
class TestMe
{
    public static int StaticField;
}

void TestMethod()
{
    Console.WriteLine(nameof(TestMe.StaticField));  // IL2026 Don't
}
```

Since linker doesn't produce these warnings, the analyzer probably shouldn't either.

**Comment by tlakollo** [comment]
The analyzer doesn't see that the call to `nameof` doesn't imply a reference to the member. Internally we will convert the member reference into a string load (`ldstr "StaticField"` in IL) just because the nameof() is a special keyword. I will add a special case to look for `nameof` operation in the analyzer.
