### ISSUE TITLE
TestGetDisplayName is flaky

### ISSUE THREAD

**Issue by jtschuster** [dotnet/linker#2693]
TestGetDisplayName on Linux sometimes fails randomly, then will pass on a retry. It seems to be with formatting generic parameters.

**Comment by jtschuster** [comment]
I'm running into this issue on Windows too now

**Comment by marek-safar** [comment]
I believe test are run in random order so there will be some test with side effects causing this

**Comment by tlakollo** [comment]
I haven't found the source of the error but seems like the test infra has some kind of conflict because there are two different uses of GenericClassMultipleParameters.
https://github.com/dotnet/linker/blob/main/test/Mono.Linker.Tests/Tests/GetDisplayNameTests.cs#L166
https://github.com/dotnet/linker/blob/main/test/Mono.Linker.Tests/Tests/GetDisplayNameTests.cs#L195
Removing one, or renaming one of the methods to something like GenericClassMultipleParameters2 fixes the issue.

**Comment by tlakollo** [comment]
Went through the test with Sven, we couldn't find the exact place in Cecil for which the race condition happens, but Sven suggested using the NonParallelizable attribute for this test, instead of just avoiding one instance of the problem by changing names
