### ISSUE TITLE
ILLink MSBuild target does not remove native libraries

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/linker#2853]
Building an [Android application](https://github.com/xamarin/net6-samples) with the linker enabled, removes `System.IO.Compression.dll` because it is unused:

```
ILLink: Output action:   Delete assembly: System.IO.Compression, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
```

Yet the `libSystem.IO.Compression.Native.so` file remains:

```
ResolvedFileToPublish
    C:\src\xamarin-android\packages\microsoft.netcore.app.runtime.android-arm\5.0.0-rc.1.20425.16\runtimes\android-arm\native\libSystem.IO.Compression.Native.a
    C:\src\xamarin-android\packages\microsoft.netcore.app.runtime.android-arm\5.0.0-rc.1.20425.16\runtimes\android-arm\native\libSystem.IO.Compression.Native.so
```

Should the linker remove these native libraries as well?

Maybe something like:

```xml
<ResolvedFileToPublish Remove="@(ManagedAssemblyToLink->'lib%(Filename).Native.*')" /> 
```

https://github.com/dotnet/sdk/blob/1e6accd2198c34284f7d83cd17f5bf49f3f8c52d/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILLink.targets#L45

/cc @marek-safar

**Comment by jonathanpeppers** [comment]
@marek-safar @vitek-karas @sbomer 

I moved this issue here to dotnet/linker. We're having a similar issue in .NET 7 MAUI, where they want to add an optional "maps" component. Even if it was a new assembly, there is a Google maps `.aar` file -- that we somehow want to exclude from apps if the linker trims the `Microsoft.Maui.Maps` assembly completely away.

Is there a way we can solve the problem above around `libSystem.IO.Compression.Native.so` at the same time? I'm open to something we can do in the Android workload or if a linker feature is best. Thanks.

**Comment by vitek-karas** [comment]
I think this is more solvable in Android since AOT builds (not that Android does AOT only, but it can do AOT) already rely on the `--output-pinvokes` feature of the linker. And so just like the AOT which will remove pinvokes which are not used, we could use that info to remove native libraries even without AOT. This can work in Android since it's been this way for a long time and so all the scenarios where this matters are already used to it.

Outside of Android, there's a larger risk of breaking things with a general solution (we could do the PInvoke tracking for example) because there are APIs which let you load native library from code directly without PInvoke and currently we have no mechanism to even detect those let alone deal with them somehow.

Alternatively we could have a "one-of" solution, like the above proposed metadata item and we would only remove libraries which are tied to a managed assembly this way.

For .NET 7 I think the Android only solution is workable, but the general linker based solution is a harder sell - it's unclear how to do it and it's relatively risky (if we pick the general solution).

@MichalStrehovsky how does NativeAOT handle PInvokes - do we leave the native library as a file on disk and PInvokes are generally "ignored" (as in, not trimmed really).

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky how does NativeAOT handle PInvokes - do we leave the native library as a file on disk and PInvokes are generally "ignored" (as in, not trimmed really).

NativeAOT has [a mechanism](https://github.com/dotnet/runtime/blob/943da70fb0701f1749d0fb058f8af2fdff65cc2c/src/coreclr/nativeaot/docs/interop.md) to link native dependencies statically. Libraries that we ship are on this plan. We ship static libraries and pass them to the linker. Linker will ignore the static libraries if there's no references to their symbols. The "trimming" naturally falls out from that.

Native libraries that are not on this plan are copied with the app as Content. We don't know if/how they're used. Maybe p/invokes were all the references to them and we could delete them, but maybe not. We don't even know what all the possible p/invokes were because we only look at the parts of the app that are used.

(Note I use the terms link/linker in it's original meaning, not as the overload of the term used in this repo.)

**Comment by jonathanpeppers** [comment]
I filed https://github.com/xamarin/xamarin-android/issues/7114, I think we could probably use `--output-pinvokes` exclude `.so` files from apps that aren't used.

Maybe a long term goal would be to use a native linker to link everything into a single `.so` file -- removing what it can along the way? That second part sounds a lot more involved, probably something for the future.
